global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ws-chat'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app1:8080', 'app2:8080']
        labels:
          group: 'ws-chat'
